-- Trips and recommendations with collaborative features
SET search_path TO hackathon;

-- Trips table
CREATE TABLE IF NOT EXISTS trips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  destination TEXT NOT NULL,
  country TEXT,
  start_date DATE,
  end_date DATE,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'planning', -- planning, active, completed, cancelled
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Trip participants (many-to-many, includes owner)
CREATE TABLE IF NOT EXISTS trip_participants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'participant', -- owner, participant
  joined_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(trip_id, user_id)
);

-- Recommendations stored in DB (generated by agent or added manually)
CREATE TABLE IF NOT EXISTS recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  external_id TEXT NOT NULL, -- Original ID from agent (e.g., "event-pakapikumatk-pirita-2025-12-06-1100")
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN ('event', 'location')),
  title TEXT NOT NULL,
  description TEXT,
  venue JSONB, -- { name, address, neighborhood, lat, lng }
  address TEXT,
  
  -- Event-specific
  start_date_time TIMESTAMPTZ,
  end_date_time TIMESTAMPTZ,
  
  -- Location-specific
  operating_hours JSONB, -- { summary, details }
  uniqueness_reason TEXT,
  
  -- Common fields
  tags TEXT[],
  tourist_trap INT CHECK (tourist_trap >= 0 AND tourist_trap <= 100),
  price JSONB, -- { amount, currency, note }
  sources JSONB, -- Array of { url, type, note }
  languages TEXT[],
  interest_fit TEXT,
  confidence NUMERIC,
  
  -- Metadata
  raw_data JSONB, -- Original full JSON from agent
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  
  UNIQUE(trip_id, external_id)
);

-- Update vote tables to reference recommendations properly
-- Drop old constraints if they exist and recreate
ALTER TABLE recommendation_votes 
  DROP CONSTRAINT IF EXISTS recommendation_votes_recommendation_id_fkey;

-- Add foreign key to recommendations table (optional, external_id based)
-- We keep recommendation_id as TEXT to support both DB IDs and external IDs

-- Indexes
CREATE INDEX IF NOT EXISTS idx_trips_owner_id ON trips(owner_id);
CREATE INDEX IF NOT EXISTS idx_trips_status ON trips(status);
CREATE INDEX IF NOT EXISTS idx_trip_participants_trip_id ON trip_participants(trip_id);
CREATE INDEX IF NOT EXISTS idx_trip_participants_user_id ON trip_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_trip_id ON recommendations(trip_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_external_id ON recommendations(external_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_type ON recommendations(type);

